using NetflixDatabaseTests;
using NetflixDatabaseTests.EntityFramework;
using NetflixDatabaseTests.Mongo;
class Program
{
    static void Main(string[] args)
    {
        var stopwatch = new System.Diagnostics.Stopwatch();
        string filePath = @"..\..\..\operation_times.txt";

        //ENTITY FRAMEWORK FUNCTIONS START
        var EfContext = new EfContext();
        stopwatch.Start();
        EfContext.InsertMultipleUsers(1);
        stopwatch.Stop();
        SaveOperationTimeToFile("EF Create(1)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        EfContext.InsertMultipleUsers(100);
        stopwatch.Stop();
        SaveOperationTimeToFile("EF Create(100)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        EfContext.InsertMultipleUsers(1000);
        stopwatch.Stop();
        SaveOperationTimeToFile("EF Create(1000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        EfContext.InsertMultipleUsers(10000);
        stopwatch.Stop();
        SaveOperationTimeToFile("EF Create(10000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        EfContext.InsertMultipleUsers(100000);
        stopwatch.Stop();
        SaveOperationTimeToFile("EF Create(100000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        EfContext.InsertMultipleUsers(500000);
        stopwatch.Stop();
        SaveOperationTimeToFile("EF Create(500000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        EfContext.InsertMultipleUsers(1000000);
        stopwatch.Stop();
        SaveOperationTimeToFile("EF Create(1000000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();

        stopwatch.Start();
        EfContext.GetMultipleUsers(1);
        stopwatch.Stop();
        SaveOperationTimeToFile("EF Read(1)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        EfContext.GetMultipleUsers(100);
        stopwatch.Stop();
        SaveOperationTimeToFile("EF Read(100)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        EfContext.GetMultipleUsers(1000);
        stopwatch.Stop();
        SaveOperationTimeToFile("EF Read(1000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        EfContext.GetMultipleUsers(10000);
        stopwatch.Stop();
        SaveOperationTimeToFile("EF Read(10000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        EfContext.GetMultipleUsers(100000);
        stopwatch.Stop();
        SaveOperationTimeToFile("EF Read(100000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        EfContext.GetMultipleUsers(500000);
        stopwatch.Stop();
        SaveOperationTimeToFile("EF Read(500000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        EfContext.GetMultipleUsers(1000000);
        stopwatch.Stop();
        SaveOperationTimeToFile("EF Read(1000000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();

        stopwatch.Start();
        EfContext.UpdateMultipleUsers(1);
        stopwatch.Stop();
        SaveOperationTimeToFile("EF Update(1)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        EfContext.UpdateMultipleUsers(100);
        stopwatch.Stop();
        SaveOperationTimeToFile("EF Update(100)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        EfContext.UpdateMultipleUsers(1000);
        stopwatch.Stop();
        SaveOperationTimeToFile("EF Update(1000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        EfContext.UpdateMultipleUsers(10000);
        stopwatch.Stop();
        SaveOperationTimeToFile("EF Update(10000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        EfContext.UpdateMultipleUsers(100000);
        stopwatch.Stop();
        SaveOperationTimeToFile("EF Update(100000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        EfContext.UpdateMultipleUsers(500000);
        stopwatch.Stop();
        SaveOperationTimeToFile("EF Update(500000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        EfContext.UpdateMultipleUsers(1000000);
        stopwatch.Stop();
        SaveOperationTimeToFile("EF Update(1000000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();

        stopwatch.Start();
        EfContext.DeleteMultipleUsers(1);
        stopwatch.Stop();
        SaveOperationTimeToFile("EF Delete(1)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        EfContext.DeleteMultipleUsers(100);
        stopwatch.Stop();
        SaveOperationTimeToFile("EF Delete(100)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        EfContext.DeleteMultipleUsers(1000);
        stopwatch.Stop();
        SaveOperationTimeToFile("EF Delete(1000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        EfContext.DeleteMultipleUsers(10000);
        stopwatch.Stop();
        SaveOperationTimeToFile("EF Delete(10000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        EfContext.DeleteMultipleUsers(100000);
        stopwatch.Stop();
        SaveOperationTimeToFile("EF Delete(100000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        EfContext.DeleteMultipleUsers(500000);
        stopwatch.Stop();
        SaveOperationTimeToFile("EF Delete(500000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        EfContext.DeleteMultipleUsers(1000000);
        stopwatch.Stop();
        SaveOperationTimeToFile("EF Delete(1000000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        //ENTITY FRAMEWORK FUNCTIONS STOP

        //ADO FUNCTIONS START
        var dbAccess = new ADOdBAccess();
        stopwatch.Start();
        dbAccess.InsertMultipleUsers(1);
        stopwatch.Stop();
        SaveOperationTimeToFile("ADO Create(1)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        dbAccess.InsertMultipleUsers(100);
        stopwatch.Stop();
        SaveOperationTimeToFile("ADO Create(100)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        dbAccess.InsertMultipleUsers(1000);
        stopwatch.Stop();
        SaveOperationTimeToFile("ADO Create(1000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        dbAccess.InsertMultipleUsers(10000);
        stopwatch.Stop();
        SaveOperationTimeToFile("ADO Create(10000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        dbAccess.InsertMultipleUsers(100000);
        stopwatch.Stop();
        SaveOperationTimeToFile("ADO Create(100000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        dbAccess.InsertMultipleUsers(500000);
        stopwatch.Stop();
        SaveOperationTimeToFile("ADO Create(500000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        dbAccess.InsertMultipleUsers(1000000);
        stopwatch.Stop();
        SaveOperationTimeToFile("ADO Create(1000000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();

        stopwatch.Start();
        dbAccess.GetMultipleUsers(1);
        stopwatch.Stop();
        SaveOperationTimeToFile("ADO Read(1)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        dbAccess.GetMultipleUsers(100);
        stopwatch.Stop();
        SaveOperationTimeToFile("ADO Read(100)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        dbAccess.GetMultipleUsers(1000);
        stopwatch.Stop();
        SaveOperationTimeToFile("ADO Read(1000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        dbAccess.GetMultipleUsers(10000);
        stopwatch.Stop();
        SaveOperationTimeToFile("ADO Read(10000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        dbAccess.GetMultipleUsers(100000);
        stopwatch.Stop();
        SaveOperationTimeToFile("ADO Read(100000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        dbAccess.GetMultipleUsers(500000);
        stopwatch.Stop();
        SaveOperationTimeToFile("ADO Read(500000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        dbAccess.GetMultipleUsers(1000000);
        stopwatch.Stop();
        SaveOperationTimeToFile("ADO Read(1000000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();

        stopwatch.Start();
        dbAccess.UpdateMultipleUsers(1);
        stopwatch.Stop();
        SaveOperationTimeToFile("ADO Update(1)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        dbAccess.UpdateMultipleUsers(100);
        stopwatch.Stop();
        SaveOperationTimeToFile("ADO Update(100)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        dbAccess.UpdateMultipleUsers(1000);
        stopwatch.Stop();
        SaveOperationTimeToFile("ADO Update(1000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        dbAccess.UpdateMultipleUsers(10000);
        stopwatch.Stop();
        SaveOperationTimeToFile("ADO Update(10000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        dbAccess.UpdateMultipleUsers(100000);
        stopwatch.Stop();
        SaveOperationTimeToFile("ADO Update(100000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        dbAccess.UpdateMultipleUsers(500000);
        stopwatch.Stop();
        SaveOperationTimeToFile("ADO Update(500000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        dbAccess.UpdateMultipleUsers(1000000);
        stopwatch.Stop();
        SaveOperationTimeToFile("ADO Update(1000000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();


        stopwatch.Start();
        dbAccess.DeleteMultipleUsers(1);
        stopwatch.Stop();
        SaveOperationTimeToFile("ADO Delete(1)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        dbAccess.DeleteMultipleUsers(100);
        stopwatch.Stop();
        SaveOperationTimeToFile("ADO Delete(100)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        dbAccess.DeleteMultipleUsers(1000);
        stopwatch.Stop();
        SaveOperationTimeToFile("ADO Delete(1000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        dbAccess.DeleteMultipleUsers(10000);
        stopwatch.Stop();
        SaveOperationTimeToFile("ADO Delete(10000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        dbAccess.DeleteMultipleUsers(100000);
        stopwatch.Stop();
        SaveOperationTimeToFile("ADO Delete(100000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        dbAccess.DeleteMultipleUsers(500000);
        stopwatch.Stop();
        SaveOperationTimeToFile("ADO Delete(500000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        dbAccess.DeleteMultipleUsers(1000000);
        stopwatch.Stop();
        SaveOperationTimeToFile("ADO Delete(1000000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        //ADO FUNCTIONS STOP


        //MONGO FUNCTIONS START
        var mongoDBAccess = new MongoDBAccess();
        stopwatch.Start();
        mongoDBAccess.InsertMultipleUsers(1).Wait();
        stopwatch.Stop();
        SaveOperationTimeToFile("Mongo Create(1)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        mongoDBAccess.InsertMultipleUsers(100).Wait();
        stopwatch.Stop();
        SaveOperationTimeToFile("Mongo Create(100)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        mongoDBAccess.InsertMultipleUsers(1000).Wait();
        stopwatch.Stop();
        SaveOperationTimeToFile("Mongo Create(1000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        mongoDBAccess.InsertMultipleUsers(10000).Wait();
        stopwatch.Stop();
        SaveOperationTimeToFile("Mongo Create(10000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        mongoDBAccess.InsertMultipleUsers(100000).Wait();
        stopwatch.Stop();
        SaveOperationTimeToFile("Mongo Create(100000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        mongoDBAccess.InsertMultipleUsers(500000).Wait();
        stopwatch.Stop();
        SaveOperationTimeToFile("Mongo Create(500000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        mongoDBAccess.InsertMultipleUsers(1000000).Wait();
        stopwatch.Stop();
        SaveOperationTimeToFile("Mongo Create(1000000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();

        stopwatch.Start();
        mongoDBAccess.GetMultipleUsers(1).Wait();
        stopwatch.Stop();
        SaveOperationTimeToFile("Mongo Read(1)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        mongoDBAccess.GetMultipleUsers(100).Wait();
        stopwatch.Stop();
        SaveOperationTimeToFile("Mongo Read(100)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        mongoDBAccess.GetMultipleUsers(1000).Wait();
        stopwatch.Stop();
        SaveOperationTimeToFile("Mongo Read(1000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        mongoDBAccess.GetMultipleUsers(10000).Wait();
        stopwatch.Stop();
        SaveOperationTimeToFile("Mongo Read(10000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        mongoDBAccess.GetMultipleUsers(100000).Wait();
        stopwatch.Stop();
        SaveOperationTimeToFile("Mongo Read(100000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        mongoDBAccess.GetMultipleUsers(500000).Wait();
        stopwatch.Stop();
        SaveOperationTimeToFile("Mongo Read(500000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        mongoDBAccess.GetMultipleUsers(1000000).Wait();
        stopwatch.Stop();
        SaveOperationTimeToFile("Mongo Read(1000000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();

        stopwatch.Start();
        mongoDBAccess.UpdateMultipleUsers(1).Wait();
        stopwatch.Stop();
        SaveOperationTimeToFile("Mongo Update(1)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        mongoDBAccess.UpdateMultipleUsers(100).Wait();
        stopwatch.Stop();
        SaveOperationTimeToFile("Mongo Update(100)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        mongoDBAccess.UpdateMultipleUsers(1000).Wait();
        stopwatch.Stop();
        SaveOperationTimeToFile("Mongo Update(1000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        mongoDBAccess.UpdateMultipleUsers(10000).Wait();
        stopwatch.Stop();
        SaveOperationTimeToFile("Mongo Update(10000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        mongoDBAccess.UpdateMultipleUsers(100000).Wait();
        stopwatch.Stop();
        SaveOperationTimeToFile("Mongo Update(100000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        mongoDBAccess.UpdateMultipleUsers(500000).Wait();
        stopwatch.Stop();
        SaveOperationTimeToFile("Mongo Update(500000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        mongoDBAccess.UpdateMultipleUsers(1000000).Wait();
        stopwatch.Stop();
        SaveOperationTimeToFile("Mongo Update(1000000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();

        stopwatch.Start();
        mongoDBAccess.DeleteMultipleUsers(1).Wait();
        stopwatch.Stop();
        SaveOperationTimeToFile("Mongo Delete(1)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        mongoDBAccess.DeleteMultipleUsers(100).Wait();
        stopwatch.Stop();
        SaveOperationTimeToFile("Mongo Delete(100)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        mongoDBAccess.DeleteMultipleUsers(1000).Wait();
        stopwatch.Stop();
        SaveOperationTimeToFile("Mongo Delete(1000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        mongoDBAccess.DeleteMultipleUsers(10000).Wait();
        stopwatch.Stop();
        SaveOperationTimeToFile("Mongo Delete(10000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        mongoDBAccess.DeleteMultipleUsers(100000).Wait();
        stopwatch.Stop();
        SaveOperationTimeToFile("Mongo Delete(100000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        mongoDBAccess.DeleteMultipleUsers(500000).Wait();
        stopwatch.Stop();
        SaveOperationTimeToFile("Mongo Delete(500000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        stopwatch.Start();
        mongoDBAccess.DeleteMultipleUsers(1000000).Wait();
        stopwatch.Stop();
        SaveOperationTimeToFile("Mongo Delete(1000000)", stopwatch.ElapsedMilliseconds, filePath);
        stopwatch.Reset();
        //MONGO FUNCTIONS STOP
    }
    static void SaveOperationTimeToFile(string operationName, long elapsedMilliseconds, string filePath)
    {
        try
        {
            using (StreamWriter writer = File.AppendText(filePath))
            {
                writer.WriteLine(operationName + ": " + elapsedMilliseconds + " ms");
            }
        }
        catch (Exception e)
        {
            Console.WriteLine("Error writing to file: " + e.Message);
        }
    }

}



